### ISSUE TITLE
github support for dixTable.py

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-wiki-tools#1]
Scrape Apertium repositories on GitHub instead of svn in [dixTable.py](https://github.com/apertium/apertium-wiki-tools/blob/master/dixTable.py).

**Comment by sushain97** [comment]
This is probably a good GCI task. `stats-server` + Github's SVN bridge should make it relatively straightforward.

**Comment by jonorthwash** [comment]
Agreed—I think we even discussed this for this last year but either didn't post it or didn't get a student to work on it.  And of course, this year's GCI is a long ways off (and there's always the potential that Apertium won't participate).  Whenever it gets done, at least, this issue is open until the functionality is added so that we don't forget about it!

(Another task idea: have it update existing tables automatically; and another task idea: implement that into [begiak](https://github.com/apertium/phenny/)!)
